version: '3'
services:
  postgres:
    image: sunyub/postgres
    container_name: postgres-container
    environment:
      POSTGRES_DB: "reserv"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    volumes:
      - reservdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  spring-boot-app:
    image: sunyub/backend-server
    container_name: backend-server
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
  next-js-app:
    image: sunyub/frontend-server
    container_name: frontend-server
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  redis:
    image: sunyub/redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  reservdata:
  redis-data: